validate_paths: false

bucket: dataset
dataset_prefix: polyp_dataset

model: UNet
epoch: 30
lr: 0.0001
batchsize: 4
trainsize: 352
clip: 0.5
scheduler_patience: 5
decay_rate: 0.1
augmentation: true

train_path: s3://dataset/polyp_dataset/TrainDataset
test_path: s3://dataset/polyp_dataset/TestDataset
train_save: /mnt/outputs/model_pth

seed: 1234
log_level: INFO
is_final_training: true

mlflow:
  enable: true
  experiment_name: PolypSegmentation
  run_name: auto
  tracking_uri: http://mlflow-service.mlflow.svc.cluster.local:5001
  s3_endpoint_url: http://minio-service.mlflow.svc.cluster.local:9000
  tags:
    project: PolypSegmentation
    environment: kubeflow
    author: KubeflowPipeline

ray:
  address:  ray://kuberay-raycluster-head-svc.development:10001
  namespace: development
  local_mode: false
  storage_path: /mnt/outputs/ray-results
  patch_runtime_env: false
  scaling:
    num_workers: 1
    use_gpu: auto
    resources_per_worker:
      CPU: 1
      GPU: 0
  runtime_env:
    working_dir: '.'
    excludes: [
      ".git/**",
      ".venv/**",
      "**/__pycache__/**",
      "data/**",
      "datasets/**",
      "checkpoints/**",
      "*.pt",
      "*.pth",
      "*.log",
      "*.zip",
      "*.tar",
    ]
    env_vars:
      PYTHONUNBUFFERED: "1"

tuning:
  enable: true
  metric: best_dice_score
  mode: max
  num_samples: 4
  search_space:
    batchsize: [2, 4, 6]
    lr: [0.001, 0.0005, 0.0001]
    trainsize: [320, 352]
    decay_rate: [0.05, 0.1]
    clip: [0.5, 0.7]