apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
