prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 15d
    scrapeInterval: 15s
    storageSpec:
      volumeClaimTemplate:
        metadata:
          labels:
            app.kubernetes.io/name: kube-prometheus-stack
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
          storageClassName: standard-rwo
    additionalScrapeConfigs:
      - job_name: triton-gateway
        metrics_path: /metrics
        scrape_interval: 15s
        static_configs:
          - targets:
              - polyp-segmentation-cpu-transformer.kserve-inference.svc:80
