apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: mlflow-postgres # this label is used to match the deployment selector